export * from "./MainPage";
export * from "./ProductPage";
export * from "./ProductdetailsPage";
export * from "./CartPage";
export * from "./Auth/LoginPage";
export * from "./Auth/SignUpPage";
export * from "./CategoryPage";
export * from "./UserPage";
export * from "./TestPage";
